import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const read = (path: string) => readFileSync(new URL(path, import.meta.url), "utf8");
const config = read("./vite.config.ts");
const entry = read("./index.html");
const adminView = read("./src/views/AdminView.vue");
const contentView = read("./src/views/ContentSettingsView.vue");
const modal = read("./src/components/ui/Modal.vue");
const integrationsView = read("./src/views/CreatorIntegrationsView.vue");
const dispatchView = read("./src/views/CreatorDispatchView.vue");
const calendarView = read("./src/views/CalendarView.vue");
const assetsView = read("./src/views/AssetsView.vue");
const relationshipsView = read("./src/views/RelationshipsView.vue");
const feedView = read("./src/views/FeedView.vue");
const visualView = read("./src/views/CreatorVisualView.vue");
const logsView = read("./src/views/InteractionLogsView.vue");
const apiTypes = read("./src/api.d.ts");

test("Vite configuration uses the ESM-safe root and Vue entry rewrite", () => {
  assert.match(config, /fileURLToPath/);
  assert.doesNotMatch(config, /__dirname/);
  assert.match(entry, /id="app"/);
  assert.match(entry, /src\/main-vue\.ts/);
  assert.match(adminView, /ContentSettingsView/);
  assert.match(contentView, /createRelationship/);
  assert.match(contentView, /createWorldEvent/);
  assert.match(contentView, /updateRelationship/);
  assert.match(contentView, /updateWorldEvent/);
  assert.match(contentView, /activeWorldId/);
  assert.match(contentView, /list-card/);
  assert.match(contentView, /form="world-form"/);
  assert.match(contentView, /form="character-form"/);
  assert.match(contentView, /form="relationship-form"/);
  assert.match(contentView, /form="event-form"/);
  assert.match(contentView, /form="lore-form"/);
  assert.match(contentView, /Trash2/);
  assert.match(contentView, /Search/);
  assert.match(contentView, /v-model="relationForm\.relationshipType"/);
  assert.match(contentView, /v-model="eventForm\.eventKey"/);
  assert.match(modal, /ui-modal-footer/);
  assert.match(modal, /overflow-y: auto/);
  assert.match(integrationsView, /import Modal/);
  assert.match(integrationsView, /form="profile-form"/);
  assert.match(integrationsView, /profile-list.*max-height/);
  assert.match(dispatchView, /candidate-list.*height:/s);
  assert.match(dispatchView, /preview-panel, \.batch-panel.*overflow-y: auto/s);
  assert.match(calendarView, /<EmptyState v-else/);
  assert.match(calendarView, /timeline, \.template-list.*overflow-y: auto/s);
  assert.match(assetsView, /<EmptyState v-else/);
  assert.match(assetsView, /sticker-grid.*overflow-y: auto/s);
  assert.match(relationshipsView, /<EmptyState v-else/);
  assert.match(feedView, /<EmptyState v-else/);
  assert.match(visualView, /identity-card.*overflow-y: auto/s);
  assert.match(logsView, /height: calc\(100dvh - 290px\)/);
  assert.match(apiTypes, /class ApiClient/);
  assert.match(apiTypes, /getWorldCalendar/);
});
