import { InteractionLogCategory, InteractionLogLevel, InteractionLogSource } from "../../../packages/contracts/src/interaction-log.ts";
import { previewMessage, redactSensitive, type InteractionLogInput, type InteractionLogRepository } from "../../../packages/database/src/interaction-log.ts";
export type WorkerLogger = InteractionLogRepository;
export interface WorkerLogEvent { readonly action?: string; readonly event?: string; readonly phase?: string; readonly outcome?: string; readonly correlationId: string; readonly category?: InteractionLogInput["category"]; readonly level?: InteractionLogInput["level"]; readonly entityType?: string; readonly entityId?: string; readonly occurrenceId?: string; readonly worldId?: string; readonly jobId?: string; readonly requestId?: string; readonly message?: unknown; readonly details?: unknown; readonly [key: string]: unknown; }
export async function bestEffortLog(logger: WorkerLogger | undefined, event: WorkerLogEvent): Promise<void> {
  if (!logger) return;
  try {
    const input = { level: event.level ?? InteractionLogLevel.INFO, source: InteractionLogSource.WORKER, category: event.category ?? InteractionLogCategory.SYSTEM, action: event.action ?? [event.event, event.phase].filter(Boolean).join("."), outcome: event.outcome ?? "UNKNOWN", correlationId: event.correlationId, ...(event.requestId === undefined ? {} : { requestId: event.requestId }), ...(event.worldId === undefined ? {} : { worldId: event.worldId }), ...(event.entityType === undefined ? {} : { entityType: event.entityType }), ...(event.entityId === undefined && event.occurrenceId === undefined && event.jobId === undefined ? {} : { entityId: event.entityId ?? event.occurrenceId ?? event.jobId }), ...(previewMessage(redactSensitive(event.message)) === undefined ? {} : { message: previewMessage(redactSensitive(event.message)) }), details: redactSensitive({ ...(event.occurrenceId === undefined ? {} : { occurrenceId: event.occurrenceId }), ...(event.jobId === undefined ? {} : { jobId: event.jobId }), ...(event.details === undefined ? {} : { details: event.details }) }) as Record<string, unknown> };
    await logger.append(input as InteractionLogInput);
  } catch {}
}
export function workerCorrelation(entityType: string, entityId: string, occurrenceId?: string): string { return "worker:" + entityType + ":" + entityId + (occurrenceId === undefined ? "" : ":occurrence:" + occurrenceId); }