export * from "./shared.ts";
export * from "./identity.ts";
export * from "./chat-memory.ts";
export * from "./events.ts";
export * from "./media-social.ts";
export * from "./story-content.ts";

import {
  characterSchema,
  characterVisualIdentitySchema,
  imageWorkflowTemplateSchema,
  compiledImageWorkflowSchema,
  validateImageWorkflowResultSchema,
  stickerPackSchema,
  stickerSchema,
  createStickerInputSchema,
  createStickerPackRequestSchema,
  worldLoreEntrySchema,
  createWorldLoreEntryRequestSchema,
  updateWorldLoreEntryRequestSchema,
  chatBackgroundItemSchema,
  chatBackgroundSettingsSchema,
  appearanceSettingsSchema,
  updateAppearanceSettingsRequestSchema,
  storyWorldSchema,
  relationshipStateSchema,
  relationshipEdgeSchema,
  createRelationshipEdgeRequestSchema,
  updateRelationshipEdgeRequestSchema,
  actorSessionSchema,
  actorSessionSwitchRequestSchema,
} from "./identity.ts";
import {
  conversationSchema,
  conversationMemberSchema,
  messageSchema,
  createConversationRequestSchema,
  sendMessageRequestSchema,
  requestConversationImageRequestSchema,
  memoryItemSchema,
} from "./chat-memory.ts";
import {
  eventRecurrenceSchema,
  worldEventDefinitionSchema,
  createWorldEventDefinitionRequestSchema,
  updateWorldEventDefinitionRequestSchema,
  scheduledOccurrenceSchema,
  worldCalendarSchema,
  characterPlanSchema,
  eventExecutionSchema,
  proactiveMessageBudgetSchema,
  behaviorActionSchema,
} from "./events.ts";
import {
  momentDraftSchema,
  imageJobSchema,
  imageAssetSchema,
  momentSchema,
  momentInteractionSchema,
  createMomentInteractionRequestSchema,
} from "./media-social.ts";
import {
  storyArcSchema,
  createStoryArcRequestSchema,
  updateStoryArcRequestSchema,
  storyNodeSchema,
  createStoryNodeRequestSchema,
  updateStoryNodeRequestSchema,
  storyEdgeSchema,
  createStoryEdgeRequestSchema,
  updateStoryEdgeRequestSchema,
  promptTemplateSchema,
  createPromptTemplateRequestSchema,
  updatePromptTemplateRequestSchema,
  memoryCandidateSchema,
  createMemoryCandidateRequestSchema,
  reviewMemoryCandidateRequestSchema,
  worldContextPolicySchema,
  updateWorldContextPolicyRequestSchema,
  storyGenerationJobSchema,
  createStoryGenerationJobRequestSchema,
  storyGenerationCandidateSchema,
  reviewStoryGenerationCandidateRequestSchema,
} from "./story-content.ts";

export const contractSchemas = {
  character: characterSchema,
  characterVisualIdentity: characterVisualIdentitySchema,
  imageWorkflowTemplate: imageWorkflowTemplateSchema,
  compiledImageWorkflow: compiledImageWorkflowSchema,
  validateImageWorkflowResult: validateImageWorkflowResultSchema,
  stickerPack: stickerPackSchema,
  sticker: stickerSchema,
  createStickerInput: createStickerInputSchema,
  createStickerPackRequest: createStickerPackRequestSchema,
  worldLoreEntry: worldLoreEntrySchema,
  createWorldLoreEntryRequest: createWorldLoreEntryRequestSchema,
  updateWorldLoreEntryRequest: updateWorldLoreEntryRequestSchema,
  chatBackgroundItem: chatBackgroundItemSchema,
  chatBackgroundSettings: chatBackgroundSettingsSchema,
  appearanceSettings: appearanceSettingsSchema,
  updateAppearanceSettingsRequest: updateAppearanceSettingsRequestSchema,
  storyWorld: storyWorldSchema,
  relationshipState: relationshipStateSchema,
  relationshipEdge: relationshipEdgeSchema,
  createRelationshipEdgeRequest: createRelationshipEdgeRequestSchema,
  updateRelationshipEdgeRequest: updateRelationshipEdgeRequestSchema,
  actorSession: actorSessionSchema,
  actorSessionSwitchRequest: actorSessionSwitchRequestSchema,
  conversation: conversationSchema,
  conversationMember: conversationMemberSchema,
  message: messageSchema,
  createConversationRequest: createConversationRequestSchema,
  sendMessageRequest: sendMessageRequestSchema,
  requestConversationImageRequest: requestConversationImageRequestSchema,
  memoryItem: memoryItemSchema,
  eventRecurrence: eventRecurrenceSchema,
  worldEventDefinition: worldEventDefinitionSchema,
  createWorldEventDefinitionRequest: createWorldEventDefinitionRequestSchema,
  updateWorldEventDefinitionRequest: updateWorldEventDefinitionRequestSchema,
  scheduledOccurrence: scheduledOccurrenceSchema,
  worldCalendar: worldCalendarSchema,
  characterPlan: characterPlanSchema,
  eventExecution: eventExecutionSchema,
  proactiveMessageBudget: proactiveMessageBudgetSchema,
  behaviorAction: behaviorActionSchema,
  momentDraft: momentDraftSchema,
  imageJob: imageJobSchema,
  imageAsset: imageAssetSchema,
  moment: momentSchema,
  momentInteraction: momentInteractionSchema,
  createMomentInteractionRequest: createMomentInteractionRequestSchema,
  storyArc: storyArcSchema,
  createStoryArcRequest: createStoryArcRequestSchema,
  updateStoryArcRequest: updateStoryArcRequestSchema,
  storyNode: storyNodeSchema,
  createStoryNodeRequest: createStoryNodeRequestSchema,
  updateStoryNodeRequest: updateStoryNodeRequestSchema,
  storyEdge: storyEdgeSchema,
  createStoryEdgeRequest: createStoryEdgeRequestSchema,
  updateStoryEdgeRequest: updateStoryEdgeRequestSchema,
  promptTemplate: promptTemplateSchema,
  createPromptTemplateRequest: createPromptTemplateRequestSchema,
  updatePromptTemplateRequest: updatePromptTemplateRequestSchema,
  memoryCandidate: memoryCandidateSchema,
  createMemoryCandidateRequest: createMemoryCandidateRequestSchema,
  reviewMemoryCandidateRequest: reviewMemoryCandidateRequestSchema,
  worldContextPolicy: worldContextPolicySchema,
  updateWorldContextPolicyRequest: updateWorldContextPolicyRequestSchema,
  storyGenerationJob: storyGenerationJobSchema,
  createStoryGenerationJobRequest: createStoryGenerationJobRequestSchema,
  storyGenerationCandidate: storyGenerationCandidateSchema,
  reviewStoryGenerationCandidateRequest: reviewStoryGenerationCandidateRequestSchema,
} as const;
