import { ImageJobKind, ImageJobStatus, MomentInteractionKind } from "../moments.ts";
import { MomentVisibility, MomentDraftStatus } from "../events.ts";
import { ImageAssetCategory } from "../dispatch.ts";
import type { CreateMomentInteractionRequest } from "../moments.ts";
import { type JsonSchema, idSchema, nonEmptyStringSchema, timestampSchema, stringListSchema, workflowObjectSchema } from "./shared.ts";

export const momentDraftSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "urn:living-network:moment-draft",
  title: "MomentDraft",
  type: "object",
  additionalProperties: false,
  properties: {
    id: idSchema,
    actionId: idSchema,
    executionId: idSchema,
    storyWorldId: idSchema,
    authorCharacterId: idSchema,
    visibility: { type: "string", enum: Object.values(MomentVisibility) },
    body: nonEmptyStringSchema,
    status: { type: "string", enum: Object.values(MomentDraftStatus) },
    imageJobId: idSchema,
    createdAt: timestampSchema,
    updatedAt: timestampSchema,
  },
  required: [
    "id",
    "actionId",
    "executionId",
    "storyWorldId",
    "authorCharacterId",
    "visibility",
    "body",
    "status",
    "createdAt",
    "updatedAt",
  ],
} as const satisfies JsonSchema;

export const imageJobSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "urn:living-network:image-job",
  title: "ImageJob",
  type: "object",
  additionalProperties: false,
  properties: {
    id: idSchema,
    kind: { type: "string", enum: Object.values(ImageJobKind) },
    actionId: idSchema,
    executionId: idSchema,
    storyWorldId: idSchema,
    ownerCharacterId: idSchema,
    momentDraftId: idSchema,
    workflowVersion: nonEmptyStringSchema,
    prompt: nonEmptyStringSchema,
    attempt: { type: "number", minimum: 1 },
    negativePrompt: nonEmptyStringSchema,
    seed: { type: "number", minimum: 0 },
    status: { type: "string", enum: Object.values(ImageJobStatus) },
    externalJobId: idSchema,
    mediaRef: nonEmptyStringSchema,
    failureReason: nonEmptyStringSchema,
    createdAt: timestampSchema,
    updatedAt: timestampSchema,
  },
  required: [
    "id",
    "kind",
    "actionId",
    "executionId",
    "storyWorldId",
    "ownerCharacterId",
    "workflowVersion",
    "prompt",
    "attempt",
    "status",
    "createdAt",
    "updatedAt",
  ],
} as const satisfies JsonSchema;

export const imageAssetSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "urn:living-network:image-asset",
  title: "ImageAsset",
  type: "object",
  additionalProperties: false,
  properties: {
    id: idSchema,
    category: { type: "string", enum: Object.values(ImageAssetCategory) },
    storyWorldId: idSchema,
    ownerCharacterId: idSchema,
    subjectCharacterId: idSchema,
    conversationId: idSchema,
    momentDraftId: idSchema,
    workflowVersion: nonEmptyStringSchema,
    prompt: nonEmptyStringSchema,
    negativePrompt: nonEmptyStringSchema,
    seed: { type: "number", minimum: 0 },
    mediaRef: nonEmptyStringSchema,
    createdAt: timestampSchema,
    updatedAt: timestampSchema,
  },
  required: [
    "id",
    "category",
    "storyWorldId",
    "ownerCharacterId",
    "subjectCharacterId",
    "workflowVersion",
    "prompt",
    "mediaRef",
    "createdAt",
    "updatedAt",
  ],
} as const satisfies JsonSchema;

export const momentSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "urn:living-network:moment",
  title: "Moment",
  type: "object",
  additionalProperties: false,
  properties: {
    id: idSchema,
    draftId: idSchema,
    storyWorldId: idSchema,
    authorCharacterId: idSchema,
    visibility: { type: "string", enum: Object.values(MomentVisibility) },
    audienceCharacterIds: { type: "array", items: idSchema },
    body: nonEmptyStringSchema,
    imageMediaRef: nonEmptyStringSchema,
    publishedAt: timestampSchema,
    createdAt: timestampSchema,
  },
  required: [
    "id",
    "draftId",
    "storyWorldId",
    "authorCharacterId",
    "visibility",
    "audienceCharacterIds",
    "body",
    "publishedAt",
    "createdAt",
  ],
} as const satisfies JsonSchema;

export const momentInteractionSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "urn:living-network:moment-interaction",
  title: "MomentInteraction",
  type: "object",
  additionalProperties: false,
  properties: {
    id: idSchema,
    momentId: idSchema,
    storyWorldId: idSchema,
    actorCharacterId: idSchema,
    kind: { type: "string", enum: Object.values(MomentInteractionKind) },
    text: nonEmptyStringSchema,
    replyToInteractionId: idSchema,
    createdAt: timestampSchema,
    idempotencyKey: idSchema,
  },
  required: [
    "id",
    "momentId",
    "storyWorldId",
    "actorCharacterId",
    "kind",
    "createdAt",
    "idempotencyKey",
  ],
} as const satisfies JsonSchema;

export const createMomentInteractionRequestSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "urn:living-network:create-moment-interaction-request",
  title: "CreateMomentInteractionRequest",
  type: "object",
  additionalProperties: false,
  properties: {
    id: idSchema,
    actorCharacterId: idSchema,
    kind: { type: "string", enum: Object.values(MomentInteractionKind) },
    text: nonEmptyStringSchema,
    createdAt: timestampSchema,
    idempotencyKey: idSchema,
  },
  required: ["id", "actorCharacterId", "kind", "createdAt", "idempotencyKey"],
} as const satisfies JsonSchema;
