// Repository interfaces are now defined in @living-network/ports.
// Re-export for backward compatibility.
export type {
  StoryWorldRepository,
  CharacterRepository,
  RelationshipEdgeRepository,
  ActorSessionRepository,
  ConversationRepository,
  MessageWriteResult,
  MessageRepository,
  MemoryRepository,
  WorldEventDefinitionRepository,
  ScheduledOccurrenceWriteResult,
  ScheduledOccurrenceRepository,
  CharacterPlanRepository,
  EventExecutionRepository,
  ProactiveMessageBudgetRepository,
  BehaviorActionRepository,
  MomentDraftRepository,
  ImageJobRepository,
  CharacterVisualIdentityRepository,
  ImageWorkflowTemplateRepository,
  StickerPackRepository,
  StickerRepository,
  AppearanceSettingsRepository,
  WorldLoreEntryRepository,
  StoryArcRepository,
  StoryNodeRepository,
  StoryEdgeRepository,
  PromptTemplateRepository,
  MemoryCandidateRepository,
  LlmProviderProfileRepository,
  ComfyUiSettingsRepository,
  MomentRepository,
  MomentInteractionWriteResult,
  MomentInteractionRepository,
  DomainRepositories,
  InMemoryRepositorySeed,
  WorldContextPolicyRepository,
  StoryGenerationJobRepository,
  StoryGenerationCandidateRepository,
} from "@living-network/ports";
