import assert from "node:assert/strict";
import path from "node:path";
import test from "node:test";

import type { ChatCompletionRequest, ChatCompletionResult, ChatDelta, ChatProvider } from "@living-network/ai/v2";
import type {
  V2ApprovedAssetListApiResponse,
  V2CoreExportBundleDto,
  V2CreateManualAssetApiResponse,
  V2CreateSceneGenerationJobApiResponse,
  V2GenerationJobListApiResponse,
  V2RuntimeSaveDto,
  V2RuntimeSceneDto,
  V2SceneCandidateDto,
  V2SceneGenerationJobRecord,
} from "@living-network/contracts/v2";

import { createV2ApiRuntime } from "../apps/api/src/v2/platform/runtime.ts";
import { processV2SceneGenerationJob } from "../apps/worker/src/v2/scene-generation-worker.ts";
import {
  openV2TempSqliteConnection,
  V2SqliteCandidateSubmissionPort,
  V2SqliteGenerationJobRepository,
} from "../packages/database/src/v2/index.ts";

const generatedScene = JSON.stringify({
  scene: {
    sceneId: "scene_generated",
    title: "Generated Crossing",
    body: "The reviewed path opens across the rain-soaked bridge.",
    participantCharacterIds: [],
  },
  choices: [{ label: "Return to the opening", targetSceneId: "scene_entry" }],
  validationNotes: ["Generated by the local integration provider."],
});

const onePixelPng = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/l2e3VwAAAABJRU5ErkJggg==",
  "base64",
);

function multipartBody(parts: {
  readonly fields: Readonly<Record<string, string>>;
  readonly file: { readonly fieldName: string; readonly filename: string; readonly contentType: string; readonly data: Buffer };
}): { readonly body: Buffer; readonly contentType: string } {
  const boundary = `----v2-authoring-chain-${crypto.randomUUID()}`;
  const chunks: Buffer[] = [];
  for (const [name, value] of Object.entries(parts.fields)) {
    chunks.push(Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="${name}"\r\n\r\n${value}\r\n`, "utf8"));
  }
  chunks.push(Buffer.from(
    `--${boundary}\r\nContent-Disposition: form-data; name="${parts.file.fieldName}"; filename="${parts.file.filename}"\r\nContent-Type: ${parts.file.contentType}\r\n\r\n`,
    "utf8",
  ));
  chunks.push(parts.file.data, Buffer.from(`\r\n--${boundary}--\r\n`, "utf8"));
  return {
    body: Buffer.concat(chunks),
    contentType: `multipart/form-data; boundary=${boundary}`,
  };
}

class StaticProvider implements ChatProvider {
  public async complete(_request: ChatCompletionRequest): Promise<ChatCompletionResult> {
    return { id: "provider-success", model: "integration-model", content: generatedScene };
  }

  public async *stream(_request: ChatCompletionRequest): AsyncIterable<ChatDelta> {
    yield { id: "provider-success", model: "integration-model", content: generatedScene };
  }
}

class FailingProvider implements ChatProvider {
  public async complete(_request: ChatCompletionRequest): Promise<ChatCompletionResult> {
    throw new Error("integration provider unavailable");
  }

  public async *stream(_request: ChatCompletionRequest): AsyncIterable<ChatDelta> {
    throw new Error("integration provider unavailable");
  }
}

test("V2 API, SQLite, worker, review, release, and restart form one persisted authoring chain", async () => {
  const temp = openV2TempSqliteConnection();
  const sqlitePath = temp.path;
  const mediaRoot = path.join(path.dirname(sqlitePath), "media");
  temp.db.close();
  try {
    const runtime = createV2ApiRuntime({
      sqlitePath,
      mediaRoot,
      capabilities: {
        sceneGeneration: { enabled: true },
        assetGeneration: { enabled: false },
      },
      environmentSceneConfigured: true,
    });
    try {
      const world = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/core/worlds",
        payload: {
          storyWorldId: "world_integration",
          name: "Integration World",
          summary: "A real SQLite authoring chain.",
          idempotencyKey: "integration-world",
        },
      });
      assert.equal(world.statusCode, 201);

      const state = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/core/worlds/world_integration/state/variables",
        payload: {
          key: "Trust",
          valueType: "number",
          defaultValue: 1,
          expectedRevision: 1,
          idempotencyKey: "integration-state-trust",
        },
      });
      assert.equal(state.statusCode, 201);

      const entry = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/core/worlds/world_integration/scenes",
        payload: {
          sceneId: "scene_entry",
          title: "Entry",
          body: "The story begins here.",
          isEntry: true,
          expectedRevision: 2,
          idempotencyKey: "integration-entry",
        },
      });
      assert.equal(entry.statusCode, 201);

      const assetUpload = multipartBody({
        fields: {
          storyWorldId: "world_integration",
          title: "Bridge reference",
        },
        file: {
          fieldName: "file",
          filename: "bridge.png",
          contentType: "image/png",
          data: onePixelPng,
        },
      });
      const manualAsset = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/assets/manual",
        headers: { "content-type": assetUpload.contentType },
        payload: assetUpload.body,
      });
      assert.equal(manualAsset.statusCode, 201);
      const uploadedAsset = (manualAsset.json() as V2CreateManualAssetApiResponse).asset;
      assert.equal(uploadedAsset.sourceType, "manual");
      assert.equal(uploadedAsset.originalFilename, "bridge.png");
      assert.equal(uploadedAsset.mimeType, "image/png");
      assert.equal(uploadedAsset.byteSize, onePixelPng.byteLength);

      const media = await runtime.app.inject({
        method: "GET",
        url: uploadedAsset.mediaRef.replace("media://local/v2/assets/", "/api/v2/media/assets/"),
      });
      assert.equal(media.statusCode, 200);
      assert.equal(media.headers["content-type"], "image/png");

      const assetLibrary = await runtime.app.inject({
        method: "GET",
        url: "/api/v2/generation/assets/worlds/world_integration/library",
      });
      assert.equal(assetLibrary.statusCode, 200);
      assert.deepEqual((assetLibrary.json() as V2ApprovedAssetListApiResponse).assets.map((asset) => asset.assetId), [uploadedAsset.assetId]);

      const created = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/generation/jobs/scene",
        payload: {
          storyWorldId: "world_integration",
          baseCanonRevision: 3,
          prompt: "Generate the bridge crossing scene.",
          idempotencyKey: "integration-scene-job",
          maxAttempts: 1,
        },
      });
      assert.equal(created.statusCode, 201);
      const createdJob = (created.json() as V2CreateSceneGenerationJobApiResponse).job as V2SceneGenerationJobRecord;
      const jobs = new V2SqliteGenerationJobRepository(runtime.db);
      const workerResult = await processV2SceneGenerationJob({
        jobId: createdJob.jobId,
        kind: "scene",
        contextHash: createdJob.contextHash,
        correlationId: "integration-success",
      }, {
        jobs,
        candidateSubmission: new V2SqliteCandidateSubmissionPort(runtime.db),
        provider: new StaticProvider(),
      }, {
        now: () => new Date("2026-08-16T01:00:00.000Z"),
      });
      assert.equal(workerResult.kind, "succeeded");
      assert.equal(workerResult.job.status, "succeeded");

      const candidateList = await runtime.app.inject({
        method: "GET",
        url: "/api/v2/core/worlds/world_integration/candidates/scenes",
      });
      assert.equal(candidateList.statusCode, 200);
      const candidate = (candidateList.json() as V2SceneCandidateDto[])[0];
      assert.equal(candidate?.status, "pending");
      assert.equal(candidate?.provenance.source, "llm");

      const review = await runtime.app.inject({
        method: "POST",
        url: `/api/v2/core/worlds/world_integration/candidates/scenes/${encodeURIComponent(candidate!.candidateId)}/review`,
        payload: {
          action: "approve",
          reviewer: "integration-test",
          reason: "Candidate matches the authored world.",
          expectedRevision: 3,
          idempotencyKey: "integration-review",
        },
      });
      assert.equal(review.statusCode, 200);

      const graph = await runtime.app.inject({
        method: "GET",
        url: "/api/v2/core/worlds/world_integration/graph",
      });
      assert.equal(graph.statusCode, 200);
      assert.ok((graph.json() as { scenes: Array<{ sceneId: string }> }).scenes.some((scene) => scene.sceneId === "scene_generated"));

      const link = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/core/worlds/world_integration/choices",
        payload: {
          choiceId: "choice_to_generated",
          sourceSceneId: "scene_entry",
          targetSceneId: "scene_generated",
          label: "Cross the bridge",
          gates: [{ stateKey: "Trust", operator: "gte", value: 1 }],
          consequences: [{ stateKey: "Trust", operation: "increment", value: 2 }],
          expectedRevision: 4,
          idempotencyKey: "integration-link",
        },
      });
      assert.equal(link.statusCode, 201);

      const preflight = await runtime.app.inject({
        method: "GET",
        url: "/api/v2/core/worlds/world_integration/releases/preflight",
      });
      assert.equal(preflight.statusCode, 200);
      assert.equal((preflight.json() as { valid: boolean }).valid, true);

      const release = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/core/worlds/world_integration/releases",
        payload: {
          releaseId: "release_integration_v1",
          version: "1.0.0",
          sourceRevision: 5,
          idempotencyKey: "integration-release",
        },
      });
      assert.equal(release.statusCode, 201);

      const run = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/core/runtime/runs",
        payload: {
          runId: "run_integration",
          releaseId: "release_integration_v1",
          idempotencyKey: "integration-run",
        },
      });
      assert.equal(run.statusCode, 201);
      assert.equal((run.json() as V2RuntimeSceneDto).scene.sceneId, "scene_entry");
      assert.equal((run.json() as V2RuntimeSceneDto).availableChoices[0]?.choiceId, "choice_to_generated");

      const advanced = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/core/runtime/runs/run_integration/choices",
        payload: {
          choiceId: "choice_to_generated",
          idempotencyKey: "integration-runtime-choice",
        },
      });
      assert.equal(advanced.statusCode, 200);
      assert.equal((advanced.json() as V2RuntimeSceneDto).scene.sceneId, "scene_generated");
      assert.equal((advanced.json() as V2RuntimeSceneDto).run.stateValues.Trust, 3);

      const save = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/core/runtime/runs/run_integration/saves",
        payload: {
          saveId: "save_integration",
          label: "Integration checkpoint",
          idempotencyKey: "integration-save",
        },
      });
      assert.equal(save.statusCode, 201);
      assert.equal((save.json() as V2RuntimeSaveDto).label, "Integration checkpoint");

      const loaded = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/core/runtime/saves/save_integration/load",
        payload: {
          runId: "run_integration_restored",
          idempotencyKey: "integration-load-save",
        },
      });
      assert.equal(loaded.statusCode, 201);
      assert.equal((loaded.json() as V2RuntimeSceneDto).scene.sceneId, "scene_generated");

      const workspaceExport = await runtime.app.inject({
        method: "GET",
        url: "/api/v2/core/worlds/world_integration/export?revision=5",
      });
      assert.equal(workspaceExport.statusCode, 200);
      assert.match((workspaceExport.json() as V2CoreExportBundleDto).markdown, /Integration World/);

      const releaseExport = await runtime.app.inject({
        method: "GET",
        url: "/api/v2/core/releases/release_integration_v1/export",
      });
      assert.equal(releaseExport.statusCode, 200);
      assert.equal((releaseExport.json() as V2CoreExportBundleDto).source.releaseVersion, "1.0.0");

      const failedCreate = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/generation/jobs/scene",
        payload: {
          storyWorldId: "world_integration",
          baseCanonRevision: 5,
          prompt: "This provider call will fail.",
          idempotencyKey: "integration-failed-job",
          maxAttempts: 1,
        },
      });
      assert.equal(failedCreate.statusCode, 201);
      const failedJob = (failedCreate.json() as V2CreateSceneGenerationJobApiResponse).job as V2SceneGenerationJobRecord;
      const failure = await processV2SceneGenerationJob({
        jobId: failedJob.jobId,
        kind: "scene",
        contextHash: failedJob.contextHash,
        correlationId: "integration-failure",
      }, {
        jobs,
        candidateSubmission: new V2SqliteCandidateSubmissionPort(runtime.db),
        provider: new FailingProvider(),
      }, {
        now: () => new Date("2026-08-16T01:01:00.000Z"),
      });
      assert.equal(failure.kind, "failed_terminal");
      assert.equal(failure.job.status, "failed");
      assert.equal(failure.job.failureReason, "integration provider unavailable");
    } finally {
      await runtime.close();
    }

    const restarted = createV2ApiRuntime({ sqlitePath, mediaRoot });
    try {
      const jobsAfterRestart = await restarted.app.inject({
        method: "GET",
        url: "/api/v2/generation/worlds/world_integration/jobs",
      });
      assert.equal(jobsAfterRestart.statusCode, 200);
      const persistedJobs = (jobsAfterRestart.json() as V2GenerationJobListApiResponse).jobs;
      assert.equal(persistedJobs[0]?.status, "failed");
      assert.equal(persistedJobs[0]?.failureReason, "integration provider unavailable");
      assert.equal(persistedJobs[1]?.status, "succeeded");
      assert.ok(persistedJobs[1]?.candidateId);

      const canon = await restarted.app.inject({
        method: "GET",
        url: "/api/v2/core/worlds/world_integration/canon",
      });
      assert.equal(canon.statusCode, 200);
      assert.equal((canon.json() as { world: { revision: number } }).world.revision, 5);

      const graph = await restarted.app.inject({
        method: "GET",
        url: "/api/v2/core/worlds/world_integration/graph",
      });
      assert.ok((graph.json() as { scenes: Array<{ sceneId: string }> }).scenes.some((scene) => scene.sceneId === "scene_generated"));

      const releases = await restarted.app.inject({
        method: "GET",
        url: "/api/v2/core/worlds/world_integration/releases",
      });
      assert.deepEqual((releases.json() as Array<{ releaseId: string }>).map((item) => item.releaseId), ["release_integration_v1"]);

      const saves = await restarted.app.inject({
        method: "GET",
        url: "/api/v2/core/worlds/world_integration/runtime/saves",
      });
      assert.equal(saves.statusCode, 200);
      assert.equal((saves.json() as V2RuntimeSaveDto[])[0]?.label, "Integration checkpoint");

      const library = await restarted.app.inject({
        method: "GET",
        url: "/api/v2/generation/assets/worlds/world_integration/library",
      });
      assert.equal(library.statusCode, 200);
      assert.equal((library.json() as V2ApprovedAssetListApiResponse).assets[0]?.sourceType, "manual");
    } finally {
      await restarted.close();
    }
  } finally {
    temp.cleanup();
  }
});
