import assert from "node:assert/strict";
import test from "node:test";

import type { ChatCompletionRequest, ChatCompletionResult, ChatDelta, ChatProvider } from "@living-network/ai/v2";
import type {
  V2CreateSceneGenerationJobApiResponse,
  V2GenerationJobListApiResponse,
  V2SceneCandidateDto,
  V2SceneGenerationJobRecord,
} from "@living-network/contracts/v2";

import { createV2ApiRuntime } from "../apps/api/src/v2/platform/runtime.ts";
import { processV2SceneGenerationJob } from "../apps/worker/src/v2/scene-generation-worker.ts";
import {
  openV2TempSqliteConnection,
  V2SqliteCandidateSubmissionPort,
  V2SqliteGenerationJobRepository,
} from "../packages/database/src/v2/index.ts";

const generatedScene = JSON.stringify({
  scene: {
    sceneId: "scene_generated",
    title: "Generated Crossing",
    body: "The reviewed path opens across the rain-soaked bridge.",
    participantCharacterIds: [],
  },
  choices: [{ label: "Return to the opening", targetSceneId: "scene_entry" }],
  validationNotes: ["Generated by the local integration provider."],
});

class StaticProvider implements ChatProvider {
  public async complete(_request: ChatCompletionRequest): Promise<ChatCompletionResult> {
    return { id: "provider-success", model: "integration-model", content: generatedScene };
  }

  public async *stream(_request: ChatCompletionRequest): AsyncIterable<ChatDelta> {
    yield { id: "provider-success", model: "integration-model", content: generatedScene };
  }
}

class FailingProvider implements ChatProvider {
  public async complete(_request: ChatCompletionRequest): Promise<ChatCompletionResult> {
    throw new Error("integration provider unavailable");
  }

  public async *stream(_request: ChatCompletionRequest): AsyncIterable<ChatDelta> {
    throw new Error("integration provider unavailable");
  }
}

test("V2 API, SQLite, worker, review, release, and restart form one persisted authoring chain", async () => {
  const temp = openV2TempSqliteConnection();
  const sqlitePath = temp.path;
  temp.db.close();
  try {
    const runtime = createV2ApiRuntime({
      sqlitePath,
      capabilities: {
        sceneGeneration: { enabled: true },
        assetGeneration: { enabled: false },
      },
      environmentSceneConfigured: true,
    });
    try {
      const world = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/core/worlds",
        payload: {
          storyWorldId: "world_integration",
          name: "Integration World",
          summary: "A real SQLite authoring chain.",
          idempotencyKey: "integration-world",
        },
      });
      assert.equal(world.statusCode, 201);

      const entry = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/core/worlds/world_integration/scenes",
        payload: {
          sceneId: "scene_entry",
          title: "Entry",
          body: "The story begins here.",
          isEntry: true,
          expectedRevision: 1,
          idempotencyKey: "integration-entry",
        },
      });
      assert.equal(entry.statusCode, 201);

      const created = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/generation/jobs/scene",
        payload: {
          storyWorldId: "world_integration",
          baseCanonRevision: 2,
          prompt: "Generate the bridge crossing scene.",
          idempotencyKey: "integration-scene-job",
          maxAttempts: 1,
        },
      });
      assert.equal(created.statusCode, 201);
      const createdJob = (created.json() as V2CreateSceneGenerationJobApiResponse).job as V2SceneGenerationJobRecord;
      const jobs = new V2SqliteGenerationJobRepository(runtime.db);
      const workerResult = await processV2SceneGenerationJob({
        jobId: createdJob.jobId,
        kind: "scene",
        contextHash: createdJob.contextHash,
        correlationId: "integration-success",
      }, {
        jobs,
        candidateSubmission: new V2SqliteCandidateSubmissionPort(runtime.db),
        provider: new StaticProvider(),
      }, {
        now: () => new Date("2026-08-16T01:00:00.000Z"),
      });
      assert.equal(workerResult.kind, "succeeded");
      assert.equal(workerResult.job.status, "succeeded");

      const candidateList = await runtime.app.inject({
        method: "GET",
        url: "/api/v2/core/worlds/world_integration/candidates/scenes",
      });
      assert.equal(candidateList.statusCode, 200);
      const candidate = (candidateList.json() as V2SceneCandidateDto[])[0];
      assert.equal(candidate?.status, "pending");
      assert.equal(candidate?.provenance.source, "llm");

      const review = await runtime.app.inject({
        method: "POST",
        url: `/api/v2/core/worlds/world_integration/candidates/scenes/${encodeURIComponent(candidate!.candidateId)}/review`,
        payload: {
          action: "approve",
          reviewer: "integration-test",
          reason: "Candidate matches the authored world.",
          expectedRevision: 2,
          idempotencyKey: "integration-review",
        },
      });
      assert.equal(review.statusCode, 200);

      const graph = await runtime.app.inject({
        method: "GET",
        url: "/api/v2/core/worlds/world_integration/graph",
      });
      assert.equal(graph.statusCode, 200);
      assert.ok((graph.json() as { scenes: Array<{ sceneId: string }> }).scenes.some((scene) => scene.sceneId === "scene_generated"));

      const link = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/core/worlds/world_integration/choices",
        payload: {
          choiceId: "choice_to_generated",
          sourceSceneId: "scene_entry",
          targetSceneId: "scene_generated",
          label: "Cross the bridge",
          expectedRevision: 3,
          idempotencyKey: "integration-link",
        },
      });
      assert.equal(link.statusCode, 201);

      const release = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/core/worlds/world_integration/releases",
        payload: {
          releaseId: "release_integration_v1",
          version: "1.0.0",
          sourceRevision: 4,
          idempotencyKey: "integration-release",
        },
      });
      assert.equal(release.statusCode, 201);

      const failedCreate = await runtime.app.inject({
        method: "POST",
        url: "/api/v2/generation/jobs/scene",
        payload: {
          storyWorldId: "world_integration",
          baseCanonRevision: 4,
          prompt: "This provider call will fail.",
          idempotencyKey: "integration-failed-job",
          maxAttempts: 1,
        },
      });
      assert.equal(failedCreate.statusCode, 201);
      const failedJob = (failedCreate.json() as V2CreateSceneGenerationJobApiResponse).job as V2SceneGenerationJobRecord;
      const failure = await processV2SceneGenerationJob({
        jobId: failedJob.jobId,
        kind: "scene",
        contextHash: failedJob.contextHash,
        correlationId: "integration-failure",
      }, {
        jobs,
        candidateSubmission: new V2SqliteCandidateSubmissionPort(runtime.db),
        provider: new FailingProvider(),
      }, {
        now: () => new Date("2026-08-16T01:01:00.000Z"),
      });
      assert.equal(failure.kind, "failed_terminal");
      assert.equal(failure.job.status, "failed");
      assert.equal(failure.job.failureReason, "integration provider unavailable");
    } finally {
      await runtime.close();
    }

    const restarted = createV2ApiRuntime({ sqlitePath });
    try {
      const jobsAfterRestart = await restarted.app.inject({
        method: "GET",
        url: "/api/v2/generation/worlds/world_integration/jobs",
      });
      assert.equal(jobsAfterRestart.statusCode, 200);
      const persistedJobs = (jobsAfterRestart.json() as V2GenerationJobListApiResponse).jobs;
      assert.equal(persistedJobs[0]?.status, "failed");
      assert.equal(persistedJobs[0]?.failureReason, "integration provider unavailable");
      assert.equal(persistedJobs[1]?.status, "succeeded");
      assert.ok(persistedJobs[1]?.candidateId);

      const canon = await restarted.app.inject({
        method: "GET",
        url: "/api/v2/core/worlds/world_integration/canon",
      });
      assert.equal(canon.statusCode, 200);
      assert.equal((canon.json() as { world: { revision: number } }).world.revision, 4);

      const graph = await restarted.app.inject({
        method: "GET",
        url: "/api/v2/core/worlds/world_integration/graph",
      });
      assert.ok((graph.json() as { scenes: Array<{ sceneId: string }> }).scenes.some((scene) => scene.sceneId === "scene_generated"));

      const releases = await restarted.app.inject({
        method: "GET",
        url: "/api/v2/core/worlds/world_integration/releases",
      });
      assert.deepEqual((releases.json() as Array<{ releaseId: string }>).map((item) => item.releaseId), ["release_integration_v1"]);
    } finally {
      await restarted.close();
    }
  } finally {
    temp.cleanup();
  }
});
