import type {
  V2AssetCandidatePayload,
  V2AssetCandidateRecord,
  V2AssetGenerationJobRecord,
  V2AssetId,
  V2CandidateId,
  V2IsoDateTime,
  V2JobId,
} from "@living-network/contracts";
import { assertV2AssetCandidateInput, assertV2AssetMediaRef, type JsonObject } from "@living-network/domain";
import type {
  V2AssetCandidateRepository,
  V2AssetMediaStorePort,
  V2AssetGenerationJobQueuePayload,
  V2AssetGenerationJobRepository,
} from "@living-network/ports";
import { ComfyUiError } from "../comfyui-client.ts";
import type { ComfyUiClient } from "../comfyui-types.ts";

export type V2AssetGenerationWorkerResultKind =
  | "succeeded"
  | "failed_retryable"
  | "failed_terminal"
  | "skipped_active"
  | "skipped_terminal";

export interface V2AssetGenerationWorkerResult {
  readonly kind: V2AssetGenerationWorkerResultKind;
  readonly job: V2AssetGenerationJobRecord;
  readonly candidateId?: V2CandidateId;
  readonly error?: string;
}

export interface V2AssetGenerationWorkerDependencies {
  readonly jobs: V2AssetGenerationJobRepository;
  readonly candidates: V2AssetCandidateRepository;
  readonly comfyUi: ComfyUiClient;
  readonly mediaStore?: V2AssetMediaStorePort;
}

export interface V2AssetGenerationWorkerOptions {
  readonly now?: () => Date;
  readonly leaseMs?: number;
}

const DEFAULT_LEASE_MS = 5 * 60 * 1000;

function iso(date: Date): V2IsoDateTime {
  return date.toISOString() as V2IsoDateTime;
}

function addMs(date: Date, ms: number): Date {
  return new Date(date.getTime() + ms);
}

function terminal(status: V2AssetGenerationJobRecord["status"]): boolean {
  return status === "succeeded" || status === "failed" || status === "cancelled";
}

function retryable(error: unknown): boolean {
  return error instanceof ComfyUiError
    ? error.retryable
    : typeof error === "object" &&
      error !== null &&
      "retryable" in error &&
      (error as { readonly retryable?: unknown }).retryable === true;
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function candidateIdFor(jobId: V2JobId): V2CandidateId {
  return `candidate:asset:${jobId}` as V2CandidateId;
}

function assetIdFor(jobId: V2JobId): V2AssetId {
  return `asset:${jobId}` as V2AssetId;
}

function assetPayloadFor(
  job: V2AssetGenerationJobRecord,
  mediaRef: string,
  validationNotes: readonly string[] = [],
): V2AssetCandidatePayload {
  const validated = assertV2AssetCandidateInput({
    mediaRef,
    prompt: job.prompt,
    workflowVersion: job.workflowVersion,
    ...(job.seed === undefined ? {} : { seed: job.seed }),
  });
  return {
    asset: {
      assetId: assetIdFor(job.jobId),
      mediaKind: "image",
      mediaRef: validated.mediaRef,
      prompt: validated.prompt,
      workflowVersion: validated.workflowVersion,
      sourceJobId: job.jobId,
      ...(validated.seed === undefined ? {} : { seed: validated.seed }),
    },
    validationNotes: [
      "Generated by V2 asset worker; pending creator review.",
      ...validationNotes,
    ],
  };
}

function candidateFor(input: {
  readonly job: V2AssetGenerationJobRecord;
  readonly payload: V2AssetCandidatePayload;
  readonly createdAt: V2IsoDateTime;
}): V2AssetCandidateRecord {
  return {
    candidateId: candidateIdFor(input.job.jobId),
    jobId: input.job.jobId,
    storyWorldId: input.job.storyWorldId,
    status: "pending",
    payload: input.payload,
    createdAt: input.createdAt,
  };
}

async function recoverExpiredLease(
  job: V2AssetGenerationJobRecord,
  jobs: V2AssetGenerationJobRepository,
  now: Date,
): Promise<V2AssetGenerationJobRecord> {
  if (
    (job.status === "claimed" || job.status === "running") &&
    job.leaseExpiresAt !== undefined &&
    Date.parse(job.leaseExpiresAt) <= now.getTime()
  ) {
    return jobs.recoverExpiredAssetJobLease({ jobId: job.jobId, recoveredAt: iso(now) });
  }
  return job;
}

async function controlledMediaFor(input: {
  readonly job: V2AssetGenerationJobRecord;
  readonly externalJobId: string;
  readonly sourceMediaRef: string;
  readonly mediaStore?: V2AssetMediaStorePort;
  readonly now: () => Date;
}): Promise<{ readonly mediaRef: string; readonly validationNotes: readonly string[] }> {
  try {
    return {
      mediaRef: assertV2AssetMediaRef(input.sourceMediaRef),
      validationNotes: [],
    };
  } catch (error) {
    if (input.mediaStore === undefined) throw error;
  }
  const stored = await input.mediaStore.storeGeneratedAsset({
    jobId: input.job.jobId,
    externalJobId: input.externalJobId,
    sourceMediaRef: input.sourceMediaRef,
    storedAt: iso(input.now()),
  });
  return {
    mediaRef: assertV2AssetMediaRef(stored.mediaRef),
    validationNotes: [
      `External ComfyUI media stored as ${stored.contentHash}.`,
    ],
  };
}

export async function processV2AssetGenerationJob(
  payload: V2AssetGenerationJobQueuePayload,
  dependencies: V2AssetGenerationWorkerDependencies,
  options: V2AssetGenerationWorkerOptions = {},
): Promise<V2AssetGenerationWorkerResult> {
  const now = options.now ?? (() => new Date());
  const leaseMs = options.leaseMs ?? DEFAULT_LEASE_MS;
  if (!Number.isSafeInteger(leaseMs) || leaseMs < 1) throw new RangeError("leaseMs must be a positive integer");

  const stored = await dependencies.jobs.getAssetJob(payload.jobId);
  if (stored === undefined) throw new TypeError(`Unknown V2 asset generation job: ${payload.jobId}`);
  let job = await recoverExpiredLease(stored, dependencies.jobs, now());
  if (terminal(job.status)) return { kind: "skipped_terminal", job };
  if (payload.kind !== "asset" || payload.workflowVersion !== job.workflowVersion) {
    const failed = await dependencies.jobs.markAssetJobFailed({
      jobId: job.jobId,
      failedAt: iso(now()),
      reason: "asset queue payload does not match stored job facts",
      retryable: false,
    });
    return {
      kind: "failed_terminal",
      job: failed,
      ...(failed.failureReason === undefined ? {} : { error: failed.failureReason }),
    };
  }
  if (job.status !== "queued") return { kind: "skipped_active", job };

  const claimTime = now();
  job = await dependencies.jobs.markAssetJobClaimed({
    jobId: job.jobId,
    claimedAt: iso(claimTime),
    leaseExpiresAt: iso(addMs(claimTime, leaseMs)),
  });
  if (job.status !== "claimed") return { kind: "skipped_active", job };
  job = await dependencies.jobs.markAssetJobRunning({ jobId: job.jobId, updatedAt: iso(now()) });
  if (job.status !== "running") return { kind: "skipped_active", job };

  try {
    const externalJobId = job.externalJobId ?? (await dependencies.comfyUi.submit({
      jobId: job.jobId,
      workflowVersion: job.workflowVersion,
      prompt: job.prompt,
      workflow: job.workflow as JsonObject,
      ...(job.negativePrompt === undefined ? {} : { negativePrompt: job.negativePrompt }),
      ...(job.seed === undefined ? {} : { seed: job.seed }),
    })).externalJobId;
    if (job.externalJobId === undefined) {
      job = await dependencies.jobs.markAssetJobSubmitted({
        jobId: job.jobId,
        submittedAt: iso(now()),
        externalJobId,
      });
    }
    const result = await dependencies.comfyUi.getResult(externalJobId);
    const media = await controlledMediaFor({
      job,
      externalJobId: result.externalJobId,
      sourceMediaRef: result.mediaRef,
      ...(dependencies.mediaStore === undefined ? {} : { mediaStore: dependencies.mediaStore }),
      now,
    });
    const payloadRecord = assetPayloadFor(job, media.mediaRef, media.validationNotes);
    const candidate = await dependencies.candidates.createAssetCandidate(candidateFor({
      job,
      payload: payloadRecord,
      createdAt: iso(now()),
    }));
    const succeeded = await dependencies.jobs.markAssetJobSucceeded({
      jobId: job.jobId,
      completedAt: iso(now()),
      mediaRef: media.mediaRef,
      candidateId: candidate.candidate.candidateId,
    });
    return {
      kind: "succeeded",
      job: succeeded,
      candidateId: candidate.candidate.candidateId,
    };
  } catch (error) {
    const failed = await dependencies.jobs.markAssetJobFailed({
      jobId: job.jobId,
      failedAt: iso(now()),
      reason: errorMessage(error),
      retryable: retryable(error),
    });
    return {
      kind: failed.status === "queued" ? "failed_retryable" : "failed_terminal",
      job: failed,
      ...(failed.failureReason === undefined ? {} : { error: failed.failureReason }),
    };
  }
}
